config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :shopkins, only: [:index, :show]

  root to: 'shopkins#index'
end

app/models/shopkin.rb
class Shopkin < ActiveRecord::Base
  has_many :users, through: :shopkins_users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :shopkins, through: :shopkins_users

  def num_owned(shopkin)
    self.shopkins_users.owned(shopkin.id)
  end
end

app/models/user_shopkin_attribute.rb
class UserShopkinAttribute < ActiveRecord::Base
  belongs_to :user
  belongs_to :shopkin
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/shopkins_controller.rb
class ShopkinsController < ApplicationController
  helper_method :sort_column, :sort_direction

  # GET /shopkins
  # GET /shopkins.json
  def index
    @shopkins = Shopkin.order(sort_column + ' ' + sort_direction).page(params[:page]).per(10)
  end

  # GET /shopkins/1
  # GET /shopkins/1.json
  def show
    @shopkin = Shopkin.find(params[:id])
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def shopkin_params
      params.require(:shopkin).permit(:name, :rating, :rarity, :series, :team)
    end

    def sort_column
      Shopkin.column_names.include?(params[:sort]) ? params[:sort] : 'name'
    end

    def sort_direction
      %w(asc desc).include?(params[:direction]) ?  params[:direction] : 'asc'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
end

app/helpers/shopkins_helper.rb
module ShopkinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShopkinTracker</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
  <script src="http://listjs.com/no-cdn/list.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/shopkins/index.html.erb
<h1>Shopkin Tracker</h1>

<%= form_tag shopkins_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Pic</th>
      <th><%= sortable 'rating' %></th>
      <th><%= sortable 'name' %></th>
      <th><%= sortable 'number' %></th>
      <th><%= sortable 'series' %></th>
      <th><%= sortable 'rarity' %></th>
      <th><%= sortable 'team' %></th>
    </tr>
  </thead>

  <tbody>
    <% @shopkins.each do |shopkin| %>
      <tr>
        <td><%= link_to (image_tag "#{shopkin.image}", class: 'shopkin-thumbnail'), shopkin_path("#{shopkin.id}") %></td>
        <td>
          <a href="#">1</a>
          <a href="#">2</a>
          <a href="#">3</a>
          <a href="#">4</a>
          <a href="#">5</a>
        </td>
        <td><%= shopkin.name %></td>
        <td><%= shopkin.number %></td>
        <td><%= shopkin.series %></td>
        <td><%= shopkin.rarity %></td>
        <td><%= shopkin.team %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @shopkins %>

app/views/shopkins/show.html.erb
<p>
  <strong>Image:</strong>
  <img src="<%= @shopkin.image %>" />
  <strong>Rating:</strong>
  Star
  <strong>Name:</strong>
  <%= @shopkin.name %>
  <strong>Number:</strong>
  <%= @shopkin.number %>
  <strong>Series</strong>
  <%= @shopkin.series %>
  <strong>Rarity</strong>
  <%= @shopkin.rarity %>
  <strong>Team</strong>
  <%= @shopkin.team %>
  <strong>Finish</strong>
  <%= @shopkin.finish %>
</p>

<%= link_to 'Back', shopkins_path %>